services:
  - type: web
    name: mathwiz-api
    env: python
    plan: free
    repo: https://github.com/YOUR_USERNAME/YOUR_REPO_NAME # IMPORTANT: Make sure this is your correct repo URL
    branch: main
    buildCommand: "pip install -r requirements.txt"
    # --- THIS IS THE CRITICAL FIX ---
    # This command tells Gunicorn to use Uvicorn's worker class, which can run an ASGI app (FastAPI).
    startCommand: "gunicorn -w 4 -k uvicorn.workers.UvicornWorker app:app"
    healthCheckPath: /
    envVars:
      # --- THIS IS THE SECOND CRITICAL FIX ---
      # Use a stable, long-term support Python version. 3.13 is too new for production.
      - key: PYTHON_VERSION
        value: 3.11
      - key: API_KEY
        generateValue: true # Let Render securely generate a random API key
      - key: MPLCONFIGDIR # Required for Matplotlib on some read-only filesystems
        value: /tmp/matplotlib
