services:
  - type: web
    name: mathwiz-api-v2
    env: python
    plan: free
    # Update this with your GitHub repo
    repo: https://github.com/Sugamdeol/mathwiz-api
    branch: main
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "gunicorn -w 2 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:$PORT app:app --timeout 120"
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: API_KEY
        generateValue: true
      - key: MPLCONFIGDIR
        value: /tmp/matplotlib
      - key: TMPDIR
        value: /tmp
      # Performance settings
      - key: WEB_CONCURRENCY
        value: "2"
