services:
  - type: web
    name: mathwiz-api
    runtime: python
    plan: free
    repo: https://github.com/YOUR_USERNAME/mathwiz-api
    branch: main
    buildCommand: |
      python --version
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: "gunicorn -w 1 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:$PORT app:app --timeout 120 --preload"
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: API_KEY
        generateValue: true
      - key: MPLCONFIGDIR
        value: /tmp/matplotlib
      - key: PORT
        value: "10000"
