services:

type: web
name: mathwiz-api
env: python
plan: free
buildCommand: |
python --version
pip install --upgrade pip setuptools wheel
pip install -r requirements.txt
startCommand: "gunicorn -w 2 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:$PORT app:app"
healthCheckPath: /
envVars:
key: PYTHON_VERSION
value: "3.11.9"
key: API_KEY
generateValue: true
key: MPLCONFIGDIR
value: /tmp/matplotlib
